# Generated by Django 4.2.1 on 2023-05-12 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото сотрудника')),
            ],
            options={
                'ordering': ['name', '-salary'],
            },
        ),
    ]
