# Generated by Django 4.2.1 on 2023-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0006_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='doc',
            field=models.FileField(default=None, upload_to='docs', verbose_name='Заявление'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.TextField(max_length=256, verbose_name='Причина'),
        ),
    ]
