# Generated by Django 4.2.1 on 2023-05-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0007_dayoff_doc_alter_dayoff_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='doc',
        ),
    ]
