# Generated by Django 4.2.1 on 2023-05-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0009_application_dayoff_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='doc',
        ),
    ]
