# Generated by Django 4.2.1 on 2023-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0010_remove_dayoff_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='director',
            new_name='seo_name',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_file',
            field=models.FileField(upload_to='docPattern', verbose_name='Шаблон заявления'),
        ),
    ]
