# Generated by Django 4.2.1 on 2023-05-16 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_profile', '0011_rename_director_application_seo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='id',
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
